# Generated by Django 5.2 on 2025-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='item_rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_usable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_usable_while_equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_usable_while_in_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
